server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 170596
    driver-class-name: com.mysql.cj.jdbc.Driver