version: '3'
services:
  api-tools:
    build: .
    container_name: api-tools
    image: api-tools
    restart: always
    ports:
      - "9999:8888"
    environment:
      - TZ:=Asia/Shanghai
      - privileged=true
